columns:
  age : int
  workclass : category
  fnlwgt : int
  education : category
  education_num : int
  marital_status : category
  occupation : category
  relationship : category
  race : category
  sex : category
  capital_gain : int
  capital_loss : int
  hours_per_week : int
  country : category
  salary : category

numerical_columns:
  - age
  - fnlwgt
  - education_num
  - capital_gain
  - capital_loss
  - hours_per_week


categorical_columns:
  - workclass
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - country

target_column: salary

domain_value:
  workclass:
    - State-gov
    - Self-emp-not-inc
    - Private
    - Federal-gov
    - Local-gov
    - Self-emp-inc
    - Without-pay
    - Never-worked
  education:
    - Preschool
    - 1st-4th
    - 5th-6th
    - 7th-8th
    - 9th
    - 10th
    - 11th
    - 12th
    - HS-grad
    - Some-college
    - Assoc-voc
    - Assoc-acdm
    - Bachelors
    - Masters
    - Prof-school
    - Doctorate
  
  marital_status:
    - Never-married
    - Married-civ-spouse
    - Divorced
    - Married-spouse-absent
    - Separated
    - Married-AF-spouse
    - Widowed
  
  occupation:
    - Adm-clerical
    - Exec-managerial
    - Handlers-cleaners
    - Prof-specialty
    - Other-service
    - Sales
    - Craft-repair
    - Transport-moving
    - Farming-fishing
    - Machine-op-inspct
    - Tech-support
    - Protective-serv
    - Armed-Forces
    - Priv-house-serv

  relationship:
    - Not-in-family
    - Husband
    - Wife
    - Own-child
    - Unmarried
    - Other-relative

  race:
    - White
    - Black
    - Asian-Pac-Islander
    - Amer-Indian-Eskimo
    - Other

  sex:
    - Male
    - Female
  
  country:
    - United-States
    - Cuba
    - Jamaica
    - India
    - Mexico
    - South
    - Puerto-Rico
    - Honduras
    - England
    - Canada
    - Germany
    - Iran
    - Philippines
    - Italy
    - Poland
    - Columbia
    - Cambodia
    - Thailand
    - Ecuador
    - Laos
    - Taiwan
    - Haiti
    - Portugal
    - Dominican-Republic
    - El-Salvador
    - France
    - Guatemala
    - China
    - Japan
    - Yugoslavia
    - Peru
    - Outlying-US(Guam-USVI-etc)
    - Scotland
    - Trinadad&Tobago
    - Greece
    - Nicaragua
    - Vietnam
    - Hong
    - Ireland
    - Hungary
    - Holand-Netherlands


  salary:
    - '<=50K'
    - '>50K'


